# Generated by Django 2.1 on 2018-08-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='flats',
        ),
        migrations.RemoveField(
            model_name='user',
            name='selected_flat',
        ),
    ]
