# Generated by Django 2.0.7 on 2018-07-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='home', max_length=50),
            preserve_default=False,
        ),
    ]
