# Generated by Django 2.1 on 2018-08-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0002_auto_20180819_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='commute_type',
            field=models.CharField(choices=[('bicycling', 'Cycling'), ('transit', 'Transit')], default='transit', max_length=15),
        ),
        migrations.AlterField(
            model_name='route',
            name='return_place_type',
            field=models.IntegerField(choices=[(1, 'Current flat'), (0, 'Custom place'), (2, 'None')], default=1),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_place_type',
            field=models.IntegerField(choices=[(1, 'Current flat'), (0, 'Custom place'), (2, 'None')], default=1),
        ),
    ]
