# Generated by Django 2.0.7 on 2018-07-26 23:34

import commute.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0003_auto_20180726_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='day',
            field=commute.models.Day(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
