# Generated by Django 2.0.7 on 2018-08-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0004_auto_20180726_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='return_place_type',
            field=models.CharField(choices=[(1, 'Current flat'), (0, 'Custom place')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_place_type',
            field=models.CharField(choices=[(1, 'Current flat'), (0, 'Custom place')], default=1, max_length=15),
        ),
    ]
