# Generated by Django 2.0.7 on 2018-08-04 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0005_auto_20180804_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commute.Place')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commute.Flat')),
            ],
        ),
    ]
