# Generated by Django 2.0.7 on 2018-08-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0007_auto_20180805_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='distance',
            field=models.DurationField(default=100),
            preserve_default=False,
        ),
    ]
