# Generated by Django 2.0.7 on 2018-08-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0008_distance_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='distance',
        ),
    ]
