# Generated by Django 2.0.7 on 2018-08-05 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0009_remove_distance_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='distance',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
