# Generated by Django 2.0.7 on 2018-08-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0010_distance_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='distance',
            new_name='duration',
        ),
    ]
