# Generated by Django 2.0.7 on 2018-08-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0011_auto_20180805_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='commute_type',
            field=models.CharField(choices=[('cycle', 'Cycling'), ('transit', 'Transit')], default='transit', max_length=15),
        ),
    ]
