# Generated by Django 2.0.7 on 2018-08-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0013_auto_20180808_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='return_place_type',
            field=models.IntegerField(choices=[(1, 'Current flat'), (0, 'Custom place')], default=1),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_place_type',
            field=models.IntegerField(choices=[(1, 'Current flat'), (0, 'Custom place')], default=1),
        ),
    ]
