# Generated by Django 2.0.7 on 2018-08-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0014_auto_20180808_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='day',
        ),
    ]
