# Generated by Django 2.0.7 on 2018-08-08 22:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0015_remove_route_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=None, max_length=56),
        ),
    ]
