# Generated by Django 2.0.7 on 2018-08-08 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0017_route_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
